"""Step 5 of the index build: out/*.json -> data/works-index.json, data/directors.json and
migrations/0002_seed_works.sql. Fails loudly on dashes or rupee figures in client-facing text."""
import datetime
import re
import sys

from common import *
from build_directors import resolve_director

works = load("works")
dirs = load("directors")
yt = load("yt_index")
NOW = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
live_dir_slugs = {d["fieldData"]["slug"] for d in dirs.values() if live(d)}
RUPEE = re.compile(r"₹|\bRs\.?\s?\d|\bINR\b|\blakhs?\b|\bcrores?\b", re.I)


def check_text(where, s):
    if not s:
        return
    if "—" in s or "–" in s:
        sys.exit(f"DASH in {where}: {s[:120]}")
    if RUPEE.search(s):
        sys.exit(f"RUPEE FIGURE in {where}: {s[:120]}")


def sql_str(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, (list, dict)):
        v = json.dumps(v, ensure_ascii=False)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    recs = {}
    for f in os.listdir(OUT):
        if f.endswith(".json") and not f.startswith("_"):
            with open(os.path.join(OUT, f), encoding="utf-8") as fh:
                r = json.load(fh)
                recs[r["id"]] = r
    rows = []
    missing = []
    for w in works:
        r = recs.get(w["id"])
        if not r:
            missing.append(w["fieldData"]["slug"])
            continue
        fd = w["fieldData"]
        dname, did = resolve_director(w)
        dslug = dirs[did]["fieldData"]["slug"] if did else None
        check_text(f"{fd['slug']} reference_for", r["reference_for"])
        check_text(f"{fd['slug']} outcome", r.get("outcome"))
        row = {
            "id": w["id"], "slug": fd["slug"], "client": fd.get("client"), "campaign": fd.get("campaign-name"),
            "year": (fd.get("year") or "")[:10] or None, "agency": fd.get("agency") or None,
            "director": dname, "director_slug": dslug if dslug in live_dir_slugs else None,
            "video_url": fd.get("video-url-youtube") or None,
            "format": r["format"], "duration_seconds": r.get("yt_duration"), "language": r.get("language"),
            "industry": r["industry"], "brief_type": r.get("brief_type"), "narrative_device": r.get("narrative_device"),
            "tone": r["tone"], "celebrity": r.get("celebrity"), "complexity": r["complexity"], "flags": r["flags"],
            "awards": [load("awards")[a]["fieldData"]["name"] for a in (fd.get("awards") or []) if a in load("awards")],
            "outcome": r.get("outcome"), "reference_for": r["reference_for"].strip(),
            "has_case_study": 1 if r["has_case_study"] else 0, "is_published": 1 if live(w) else 0,
            "confidence": r["confidence"], "indexed_at": NOW,
        }
        rows.append(row)
    if missing:
        print("WARNING: no extraction for", len(missing), "items:", missing[:10])
    cols = ["id", "slug", "client", "campaign", "year", "agency", "director", "director_slug", "video_url", "format",
            "duration_seconds", "language", "industry", "brief_type", "narrative_device", "tone", "celebrity", "complexity",
            "flags", "awards", "outcome", "reference_for", "has_case_study", "is_published", "confidence", "indexed_at"]
    lines = ["-- GENERATED by index/emit_seed.py on " + NOW + ". Do not edit by hand; re-run the index build.", ""]
    for row in rows:
        lines.append(f"INSERT OR REPLACE INTO works ({', '.join(cols)}) VALUES ({', '.join(sql_str(row[c]) for c in cols)});")
    drows = load("_directors", OUT)
    for d in drows:
        check_text(f"director {d['slug']} strengths", d.get("strengths"))
        vals = [d["slug"], d["name"], d.get("bio"), d["credits"], d.get("strengths"), NOW]
        lines.append(f"INSERT OR REPLACE INTO directors (slug, name, bio, credits, strengths, indexed_at) VALUES ({', '.join(sql_str(v) for v in vals)});")
    os.makedirs(os.path.join(REPO, "data"), exist_ok=True)
    with open(os.path.join(REPO, "migrations", "0002_seed_works.sql"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    with open(os.path.join(REPO, "data", "works-index.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump(rows, f, ensure_ascii=False, indent=1)
    with open(os.path.join(REPO, "data", "directors.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump([{k: v for k, v in d.items()} for d in drows], f, ensure_ascii=False, indent=1)
    longest = max(len(l) for l in lines)
    conf = {}
    for r in rows:
        conf[r["confidence"]] = conf.get(r["confidence"], 0) + 1
    print(f"{len(rows)} works rows, {len(drows)} directors; longest statement {longest} chars; confidence {conf}")
    print(f"director_slug set on {sum(1 for r in rows if r['director_slug'])} rows; no live director on {sum(1 for r in rows if not r['director_slug'])}")


if __name__ == "__main__":
    main()
